version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: python manage.py migrate
      - run: pytest --cov --cov-fail-under=80
      - run: flake8
      - setup_remote_docker:
          version: 20.10.23
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            if [ "$CIRCLE_BRANCH" == "main" ]; then
              sudo apt install -y openssh-client
              echo $KEY_SSH | base64 -d > ~/.ssh/id_rsa
              chmod 600 ~/.ssh/id_rsa
              ssh-add ~/.ssh/id_rsa
              docker build --build-arg ARG_DNS_SENTRY=$DNS_SENTRY --build-arg ARG_SECRET_KEY=$SECRET_KEY --build-arg DEBUG=$DEBUG --build-arg IPPORD=$IPPORD -t tobraider/projet13:$CIRCLE_SHA1 .
              docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
              docker push tobraider/projet13:$CIRCLE_SHA1
              ssh -v -p 18740 tobie@51.159.76.154 "source startapp $CIRCLE_SHA1"
            else
              echo "Skipping Docker build and push for branch $CIRCLE_BRANCH."
            fi

workflows:
  version: 2
  build-and-push:
    jobs:
      - build