version: 2
jobs:
  build:
    docker:
      - image: python:3.10
    steps:
      - checkout
      - run: pip install --upgrade subprocess
      - run: pip install -r requirements.txt
      - run: python manage.py migrate
      - run: pytest --cov --cov-fail-under=80
      - run: flake8
      - run:
          name: Build and push Docker image
          command: |
            if [ "$CIRCLE_BRANCH" == "main" ]; then
              pip install docker-compose
              docker build -t your-image-name:$CIRCLE_SHA1 .
              docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
              docker push your-image-name:$CIRCLE_SHA1
            else
              echo "Skipping Docker build and push for branch $CIRCLE_BRANCH."
            fi

workflows:
  version: 2
  build-and-push:
    jobs:
      - build